/*
 * Created by nphau on 01/11/2021, 00:47
 * Copyright (c) 2021 . All rights reserved.
 * Last modified 01/11/2021, 00:39
 */

package com.nphau.android.shared.ui.activities

import androidx.appcompat.app.AppCompatActivity
import androidx.viewbinding.ViewBinding
import com.nphau.android.shared.common.extensions.getBinding
import com.nphau.android.shared.ui.BindingDSL

/**
 * @author nphau (Phuc-Hau Nguyen)
 *
 * Base class which extends [AppCompatActivity] for activities that wish to bind content layout with [ViewBinding].
 * Provides a [binding] property that extends [ViewBinding] from abstract information.
 * The [binding] property ensures to be initialized before being called [onCreate].
 *
 * @param VB A generic class that extends [ViewBinding] and generated by ViewBinding on compile time.
 */
open class BindingActivity<VB : ViewBinding> : SharedActivity() {

    /**
     * Binding variable to be used for accessing views.
     * @return ViewBinding
     * */
    @BindingDSL
    protected lateinit var binding: VB

    override fun setUpBinding() {
        binding = getBinding()
        setContentView(binding.root)
    }

}